# Generated by Django 4.2.5 on 2023-09-19 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_app', '0002_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
    ]
