# Generated by Django 4.2.5 on 2023-09-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_app', '0003_folder_created_on_folder_file_folder_public_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
