# Generated by Django 4.2.5 on 2023-09-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_app', '0004_alter_folder_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='folder',
            table='folder',
        ),
    ]
