# Generated by Django 4.2.5 on 2023-09-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_app', '0006_folder_user_delete_folderdirectory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='file',
        ),
        migrations.CreateModel(
            name='MyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_driven_app.folder')),
            ],
            options={
                'db_table': 'my_files',
            },
        ),
    ]
